#!/bin/bash

remote_host=""

for arg in "$@"; do
    case "$arg" in
        -*)
            echo "Unknown argument: $arg"; exit 1 ;;
        *)
            if [ -z "$remote_host" ]; then
                remote_host="$arg"
            else
                echo "Unknown argument: $arg"; exit 1
            fi
            ;;
    esac
done

if [ -z "$remote_host" ]; then
    echo "Usage: $0 <user@host>"
    exit 1
fi

scriptDir="$(cd "$(dirname "$0")" && pwd)"
srcPath="$scriptDir/src"
remote_tmp="/tmp/spool-upload"

prescript="$scriptDir/pre-script.py"
if [ -f "$prescript" ]; then
    echo "Running pre script."
    python "$prescript"
    echo "Finished running pre script."
fi

tmpDir="./mpy"
./compile-mpy

echo "Copying files to $remote_host..."
ssh "$remote_host" "rm -rf $remote_tmp"
ssh "$remote_host" "mkdir -p $remote_tmp"
scp -r "$tmpDir/"* "$remote_host:$remote_tmp/"

echo "Clearing Pico filesystem..."
ssh -t "$remote_host" "mpremote exec \"import os; [os.remove(f) for f in os.listdir() if not os.stat(f)[0] & 0x4000]\""

echo "Copying files to Pico..."
ssh -t "$remote_host" "mpremote cp $remote_tmp/* :"

echo "Resetting Pico..."
ssh -t "$remote_host" "mpremote reset"
